### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by yuchen-guts** [ProfessorFichte/Witcher-RPG-Class#2]
I believe other mods should also be able to utilize the minerals from this mod. I'm imploring you, I truly love this mod.

**Comment by ProfessorFichte** [comment]
hi, do you mean that you want to craft Witcher Steel & Silver Swords with, silver & steel materials from other mods? In version 1.0.7 i created tags for that, you should now be able to craft silver swords with silver ingots from Mythic Metals for example if that was your question :)

**Comment by yuchen-guts** [comment]
I wish to utilize the steel and silver from this mod to craft items or tools for other mods.

**Comment by ProfessorFichte** [comment]
Well that lies not in my hands, if the mod-creators with the silver equipment from the other mods added tags to their recipe, you can easily add compat with datapacks by yourself. I will add my silver & steel ingots to the c item tags, but I cant do more, im not responsible for the recipes of other mods, I can only add tags to make compat easier

**Comment by yuchen-guts** [comment]
Thank you very much
